language: ruby
dist: trusty
rvm:
  - 2.6

before_install:
  - gem install bundler

script:
  - bundle exec rake

# deploy:
#   provider: heroku
#   app: switcher-slash-webhook
#   api_key: ${HEROKU_KEY}